### ISSUE TITLE
Error code 0

### ISSUE THREAD

**Issue by icoolguy1995** [googleads/googleads-mobile-android-examples#74] opened 2017-05-02 12:17 UTC
Hi,
I am not able to get rewarding videos, this is the error I am getting in log:

`There was a problem getting an ad response. ErrorCode: 0`
`Failed to load ad: 0`

I am initializing `MobileAds` in `onCreate` of my activity, like this:
`       MobileAds.initialize(this, "ca-app-pub-3940256099942544~3347511713");
        mAd = MobileAds.getRewardedVideoAdInstance(this);
        mAd.setRewardedVideoAdListener(this);
        loadRewardedVideoAd();`

```
private void loadRewardedVideoAd() {
        if (!mAd.isLoaded()) {
            mAd.loadAd("ca-app-pub-3940256099942544/5224354917", new AdRequest.Builder().build());
        }
    }
```
And added `AdActivity` in `manifest`

```
<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <activity
            android:name="com.google.android.gms.ads.AdActivity"        
android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />

```

And here is the printout of  `adb shell "setprop log.tag.Ads VERBOSE; logcat Ads:* *:S"`

```
adb shell "setprop log.tag.Ads VERBOSE; logcat Ads:* *:S"


--------- beginning of system
--------- beginning of crash
--------- beginning of main
05-02 17:10:14.671 15184 16051 I Ads     : Parental control value is stale. Refr
eshing.
05-02 17:10:14.935 15184 15184 I Ads     : Successfully received play store pare
ntal controls the result.
05-02 17:11:01.644 15184 16897 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:11:39.151 15184 17695 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:16:56.993 24643 25090 I Ads     : Parental control value is stale. Refr
eshing.
05-02 17:16:57.209 24643 24643 I Ads     : Successfully received play store pare
ntal controls the result.
05-02 17:17:28.212 24643 25833 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:19:59.416 28888 28888 I Ads     : Starting ad request.
05-02 17:19:59.418 28888 28888 I Ads     : Use AdRequest.Builder.addTestDevice("
D018A4A48672125CD65534B130D7ACB9") to get test ads on this device.
05-02 17:20:11.794 28888 28904 W Ads     : There was a problem getting an ad res
ponse. ErrorCode: 0
05-02 17:20:11.795 28888 28888 W Ads     : Failed to load ad: 0
05-02 17:20:47.069 24643 30138 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:39:26.539 28888 28888 D Ads     : App went background
05-02 17:39:27.462 24643 24643 D Ads     : Binding to the ad cache service.
05-02 17:39:27.465 28888 28888 I Ads     : Starting ad request.
05-02 17:39:27.466 28888 28888 I Ads     : Use AdRequest.Builder.addTestDevice("
D018A4A48672125CD65534B130D7ACB9") to get test ads on this device.
05-02 17:39:27.517 28888 24407 D Ads     : AdLoaderBackgroundTask started.
05-02 17:39:27.786 28888 24408 D Ads     : Fetching ad response from remote ad r
equest service.
05-02 17:39:27.845 24643 24643 D Ads     : Binding to the ad request service.
05-02 17:39:28.314 24643 24423 D Ads     : Starting ad request from service usin
g: AFMA_getAd
05-02 17:39:28.607 24643 24432 D Ads     : Fail to obtain recent context.
05-02 17:39:28.820 24643 24428 D Ads     : Got 2 signal pbs from gmscore
05-02 17:39:28.825 24643 24428 D Ads     : Merged client and gmscore signals
05-02 17:39:28.825 24643 24428 D Ads     : Return the combined signals
05-02 17:39:28.891 24643 24643 D Ads     : Enabling hardware acceleration on an
overlay.
05-02 17:39:47.176 28888 24370 D Ads     : Received ad response.
05-02 17:39:47.201 28888 24370 W Ads     : There was a problem getting an ad res
ponse. ErrorCode: 0
05-02 17:39:47.287 28888 28888 W Ads     : Failed to load ad: 0
05-02 17:39:47.302 28888 28888 D Ads     : Enable the debug gesture detector on
the admob ad frame.
05-02 17:39:59.173 24643 25087 D Ads     : DSID dispatcher woke up.
05-02 17:39:59.174 24643 25087 D Ads     : Running DSID refresh task.
05-02 17:39:59.587 24643 25087 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:40:45.421 28888 28888 D Ads     : App went background
05-02 17:45:05.120 28888 28888 D Ads     : App went background
05-02 17:45:26.146 24643 24643 D Ads     : Binding to the ad cache service.
05-02 17:45:26.209 28888 28888 I Ads     : Starting ad request.
05-02 17:45:26.210 28888 28888 I Ads     : Use AdRequest.Builder.addTestDevice("
D018A4A48672125CD65534B130D7ACB9") to get test ads on this device.
05-02 17:45:26.382 28888 32645 D Ads     : AdLoaderBackgroundTask started.
05-02 17:45:26.528 28888 32653 D Ads     : Fetching ad response from remote ad r
equest service.
05-02 17:45:26.545 24643 24643 D Ads     : Binding to the ad request service.
05-02 17:45:27.752 24643 32685 D Ads     : Starting ad request from service usin
g: AFMA_getAd
05-02 17:45:28.046 24643 32700 D Ads     : Fail to obtain recent context.
05-02 17:45:28.609 24643 32697 D Ads     : Got 2 signal pbs from gmscore
05-02 17:45:28.810 24643 32697 D Ads     : Merged client and gmscore signals
05-02 17:45:28.869 24643 32697 D Ads     : Return the combined signals
05-02 17:45:29.099 24643 24643 D Ads     : Enabling hardware acceleration on an
overlay.
05-02 17:45:39.077 28888 28905 D Ads     : Received ad response.
05-02 17:45:39.078 28888 28905 W Ads     : There was a problem getting an ad res
ponse. ErrorCode: 0
05-02 17:45:39.079 28888 28888 W Ads     : Failed to load ad: 0
05-02 17:45:39.114 28888 28888 D Ads     : Enable the debug gesture detector on
the admob ad frame.
05-02 17:46:02.971 24643  1240 D Ads     : DSID dispatcher woke up.
05-02 17:46:02.972 24643  1240 D Ads     : Running DSID refresh task.
05-02 17:46:03.598 24643  1240 E Ads     : Failed to connect to https://googlead
s.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-02 17:46:13.457 28888 28888 D Ads     : App went background
```

**Comment by ericleich** [comment] 2017-05-04 17:15
Thanks for the logs and sending with verbose. I was hoping to see a log with:

    D/Ads     ( 7599): AdRequestServiceImpl: Sending request: <some url>

So we could debug why your request request was failing. These logs don't have that, but fortunately I was able reproduce on my end this morning and capture a URL. So I have something for our team to debug.

Note that I'm still diagnosing this as an SDK issue, not an issue with the sample itself. And no known workaround yet.

**Comment by ericleich** [comment] 2017-05-04 18:44
I think I know what's going on.

- Last week, we fixed an issue where test requests for rewarded video would fail. This happened with a javascript (non-SDK) change.
- If you are on an emulator on Android, you are defaulted into test mode which always makes test requests.

I'm guessing you were running on emulator, and were still experiencing this old issue. Your app has to pick up the new javascript file that makes test ads work. If you make a few requests, this new file should be picked up and the problem should just start go away.

Alternatively, if you try running on device (which won't default you into test mode), you also shouldn't see this issue.

**Comment by ericleich** [comment] 2017-06-06 15:53
Closing this issue out since I believe the issue is resolved and it's been a month. Please comment if you're still having issues.

**Closed by ericleich** 2017-06-06 15:53 UTC

**Comment by RoshaanQurban** [comment] 2017-09-28 10:40
I am using sample app with own 
private static final String AD_UNIT_ID = "ca-app-pub-4426766788330575/3459404802";
    private static final String APP_ID = "ca-app-pub-4426766788330575~5347201544";
i get the errro below and the ads does not load..

09-28 18:11:28.388 28021-28021/com.google.ads.rewardedvideoexample I/Ads: Starting ad request.
09-28 18:11:28.389 28021-28021/com.google.ads.rewardedvideoexample I/Ads: This request is sent from a test device.
09-28 18:11:28.428 28021-28136/com.google.ads.rewardedvideoexample W/GooglePlayServicesUtil: Google Play services out of date.  Requires 11400000 but found 11055234
09-28 18:11:28.430 28021-28129/com.google.ads.rewardedvideoexample W/GooglePlayServicesUtil: Google Play services out of date.  Requires 11400000 but found 11055234
09-28 18:11:28.506 28021-28079/com.google.ads.rewardedvideoexample I/FA: Tag Manager is not found and thus will not be used
09-28 18:11:28.551 28021-28132/com.google.ads.rewardedvideoexample W/linker: libwebviewchromium.so: unused DT entry: type 0x6ffffffe arg 0x11a2c
09-28 18:11:28.551 28021-28132/com.google.ads.rewardedvideoexample W/linker: libwebviewchromium.so: unused DT entry: type 0x6fffffff arg 0x3
09-28 18:11:28.675 28021-28031/com.google.ads.rewardedvideoexample W/art: Suspending all threads took: 37.858ms
09-28 18:11:28.800 28021-28132/com.google.ads.rewardedvideoexample I/WebViewFactory: Loading com.google.android.webview version 58.0.3029.83 (code 302908300)
09-28 18:11:28.882 28021-28132/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
09-28 18:11:28.882 28021-28132/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
09-28 18:11:28.912 28021-28132/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
09-28 18:11:28.913 28021-28132/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
09-28 18:11:29.003 28021-28132/com.google.ads.rewardedvideoexample I/cr_LibraryLoader: Time to load native libraries: 48 ms (timestamps 7918-7966)
09-28 18:11:29.082 28021-28036/com.google.ads.rewardedvideoexample I/art: Background sticky concurrent mark sweep GC freed 19311(1364KB) AllocSpace objects, 24(785KB) LOS objects, 25% free, 5MB/7MB, paused 1.943ms total 125.930ms
09-28 18:11:29.288 28021-28132/com.google.ads.rewardedvideoexample I/chromium: [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
09-28 18:11:29.289 28021-28132/com.google.ads.rewardedvideoexample I/cr_LibraryLoader: Expected native library version number "58.0.3029.83", actual native library version number "58.0.3029.83"
09-28 18:11:29.421 28021-28021/com.google.ads.rewardedvideoexample W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
09-28 18:11:29.423 28021-28079/com.google.ads.rewardedvideoexample E/FA: Discarding data. Failed to send app launch
09-28 18:11:29.423 28021-28079/com.google.ads.rewardedvideoexample E/FA: Failed to get app instance id
09-28 18:11:29.423 28021-28079/com.google.ads.rewardedvideoexample E/FA: Failed to send current screen to service
09-28 18:11:29.423 28021-28079/com.google.ads.rewardedvideoexample E/FA: Discarding data. Failed to send event to service
09-28 18:11:29.423 28021-28079/com.google.ads.rewardedvideoexample E/FA: Failed to send current screen to service
09-28 18:11:29.611 28021-28137/com.google.ads.rewardedvideoexample E/GED: Failed to get GED Log Buf, err(0)
09-28 18:11:29.614 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: Initialized EGL, version 1.4
09-28 18:11:29.629 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: Get enable program binary service property (1)
09-28 18:11:29.629 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: Initializing program atlas...
09-28 18:11:29.639 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: Program binary detail: Binary length is 90540, program map length is 112.
09-28 18:11:29.639 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 45, and path is /dev/ashmem��Σ�LJ��߶�ٶ�M����ٶ.
09-28 18:11:29.639 28021-28137/com.google.ads.rewardedvideoexample I/OpenGLRenderer: No need to use file discriptor anymore, close fd(45).
09-28 18:11:29.651 28021-28137/com.google.ads.rewardedvideoexample I/[MALI][Gralloc]: dlopen libsec_mem.so fail
09-28 18:11:29.661 28021-28137/com.google.ads.rewardedvideoexample I/MaliEGL: [Mali]window_type=1, is_framebuffer=0, errnum = 0
09-28 18:11:29.661 28021-28137/com.google.ads.rewardedvideoexample I/MaliEGL: [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
09-28 18:11:29.661 28021-28137/com.google.ads.rewardedvideoexample I/MaliEGL: [Mali]max_allowed_dequeued_buffers=3
09-28 18:11:29.684 28021-28209/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzeig>
09-28 18:11:29.684 28021-28209/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzeig>
09-28 18:11:29.714 28021-28021/com.google.ads.rewardedvideoexample W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
09-28 18:11:29.861 28021-28021/com.google.ads.rewardedvideoexample I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
09-28 18:11:30.320 28021-28021/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
09-28 18:11:30.320 28021-28021/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
09-28 18:11:30.408 28021-28250/com.google.ads.rewardedvideoexample W/cr_BindingManager: Cannot setInForeground() - never saw a connection for the pid: 28021
09-28 18:11:30.506 28021-28021/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
09-28 18:11:30.506 28021-28021/com.google.ads.rewardedvideoexample I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
09-28 18:11:30.607 28021-28257/com.google.ads.rewardedvideoexample W/cr_media: Requires BLUETOOTH permission
09-28 18:11:30.635 28021-28021/com.google.ads.rewardedvideoexample I/Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.
09-28 18:11:30.817 28021-28036/com.google.ads.rewardedvideoexample I/art: Background partial concurrent mark sweep GC freed 9825(846KB) AllocSpace objects, 12(192KB) LOS objects, 37% free, 6MB/10MB, paused 1.786ms total 116.835ms
09-28 18:11:30.985 28021-28276/com.google.ads.rewardedvideoexample E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
09-28 18:11:31.141 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/x-adpcm-ms
09-28 18:11:31.142 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/x-adpcm-dvi-ima
09-28 18:11:31.150 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/ape
09-28 18:11:31.152 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/alac
09-28 18:11:31.161 28021-28276/com.google.ads.rewardedvideoexample W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
09-28 18:11:31.178 28021-28276/com.google.ads.rewardedvideoexample W/VideoCapabilities: Unsupported mime video/x-ms-wmv
09-28 18:11:31.181 28021-28276/com.google.ads.rewardedvideoexample W/VideoCapabilities: Unsupported mime video/divx
09-28 18:11:31.183 28021-28276/com.google.ads.rewardedvideoexample W/VideoCapabilities: Unsupported mime video/xvid
09-28 18:11:31.186 28021-28276/com.google.ads.rewardedvideoexample W/VideoCapabilities: Unsupported mime video/flv1
09-28 18:11:31.209 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/x-adpcm-ms
09-28 18:11:31.210 28021-28276/com.google.ads.rewardedvideoexample W/AudioCapabilities: Unsupported mime audio/x-adpcm-dvi-ima
09-28 18:11:31.223 28021-28276/com.google.ads.rewardedvideoexample W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
09-28 18:11:31.224 28021-28276/com.google.ads.rewardedvideoexample W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
09-28 18:11:31.355 28021-28276/com.google.ads.rewardedvideoexample W/MALI: __egl_set_error:121: [WARNING]Mali EGL errorcode: 3004
09-28 18:11:31.355 28021-28276/com.google.ads.rewardedvideoexample E/chromium: [ERROR:gl_surface_egl.cc(264)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
09-28 18:11:31.453 28021-28021/com.google.ads.rewardedvideoexample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 28021
09-28 18:11:31.591 28021-28021/com.google.ads.rewardedvideoexample I/chromium: [INFO:CONSOLE(0)] "Document was loaded from Application Cache with manifest https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.appcache", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
09-28 18:11:31.593 28021-28021/com.google.ads.rewardedvideoexample I/chromium: [INFO:CONSOLE(0)] "Application Cache Checking event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
09-28 18:11:32.390 28021-28208/com.google.ads.rewardedvideoexample I/System.out: open:https://googleads.g.doubleclick.net/mads/gma?riv=4&_activity_context=true&format=interstitial_mb&gl=US&seq_num=1&eid=318476426%2C318478235&u_sd=1.5&ms=CoACtLQ2sOx59ma-IRTx_LuCd9OauRIJyhMxBLQSU3qGKKLtHE8CSHlTs6l-WaBEEB_GimOQL9R1_4T8zQGDo_HQ8iVCRdi56acJmA2L2aBCie9OlIWR4IF44BG8ysiklwB-bwxp3kKDCuAKQJpNQ2ujG0OUKp47o_oBR2tlIoLjBMBPB9kCjvBmQXVuFO4TsT_L8xJ2aQBBebhA2zLnLUJdI-Db9xL2Cehhd7fmdzLaNsyz6ezFMQGE07NUeY4p_AtmKdXK0GtN7j45YmGLng0WXGC_BxESv0a8tqphH7P3MGv2-2yYjQTgkiRwURDHX5XXwDybpFdm8OODcQven22uGQqAAjlE0OfLrJOIUx6gMkPSVgKqpgchfXVT0hBdEi3tSHDUgfaY76jDtajtTT0H5gr4Q8nc7MHgHIfY83vzS11XUx4MW0YaGYEQAZNxAQA6bkWDuGgtjBwkJ8Ur-mZ3M27cP54hPReOeZUhc60PXUNDA-TAJLLx-1cbAKHMEiv-8yogbr2WqU_GxLI2hsZHqigrafZh13LFTPz3YclByjPnA6f5zkI9-sHW6_7JjDfe7zQNoYsxmBYUpLXapLVoyHjxcDUOWI-qbXf0uIX9rJmtfqOt4IQtiwrVwR73npQq0wKrNVI_INp91Edq-_tqpk_dBqnJddxerd0CvSnA4aNXAqcSENlG9ZoHBUzsHUrwWzRJUJM&target_api=26&hl=en&scroll_index=-1&platform=QMobile&submodel=QMobile%20W20&rm=2&android_app_muted=false&request_id=37e98ab0-dd12-417d-83dc-daf8adc6e053&am=0&cnt=1&ma=0&disable_ml=false&js=afma-sdk-a-v11400000.11400000.0&session_id=13322730495840585137&muv=0&coh=1&sp=0&gnt=0&mv=80807300.com.android.vending&android_app_volume=1&android_num_video_cache_tasks=0&is_test_device=true&adtest=on&rbv=1&cap=t&u_w=320&u_h=534&msid=com.google.ads.rewardedvideoexample&app_name=1.android.com.google.ads.rewardedvideoexample&_package_name=com.google.ads.rewardedvideoexample&an=1.android.com.google.ads.rewardedvideoexample&net=wi&u_audio=1&u_so=p&basets=2607358&currts=2607358&preqs_in_session=3&pclick=0&support_transparent_background=true&pimp=0&preqs=0&time_in_session=495973&output=html&region=mobile_app&u_tz=480&client_sdk=1&ex=1&client=ca-app-pub-3940256099942544&slotname=5224354917&gsb=wi&local_service=true&lite=false&num_ads=1&vpt=8&vfmt=18&vst=0&sdkv=o.11400000.11400000.0&sdmax=0&dmax=1&sdki=3c0d&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo&bisch=true&blev=0.17&swdr=false&cans=5&canm=false&_mv=80807300.com.android.vending&heap_free=1811328&heap_max=134217728&heap_total=8553568&wv_count=0&sai=1&blockAutoClicks=true&forceHttps=true&includeDoritos=true&tcar=87&jsv=4-production-20170927_RC00&urll=2276#_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_aso_sfv_dinm_dim_nav_navc_dinmo&eid=318476426%252C318478235&format=interstitial_mb&heap_free=1811328&heap_max=134217728&heap_total=8553568&js=afma-sdk-a-v11400000.11400000.0&msid=com.google.ads.rewardedvideoexample&preqs=0&scroll_index=-1&seq_num=1&target_api=26
09-28 18:11:32.407 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
09-28 18:11:32.412 28021-28208/com.google.ads.rewardedvideoexample I/System.out: propertyValue:true
09-28 18:11:32.414 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [CDS]rx timeout:60000
09-28 18:11:32.414 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [socket][0] connection googleads.g.doubleclick.net/216.58.209.226:443;LocalPort=48844(60000)
09-28 18:11:32.414 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [CDS]connect[googleads.g.doubleclick.net/216.58.209.226:443] tm:60
09-28 18:11:32.615 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [socket][/192.168.10.22:48844] connected
09-28 18:11:32.618 28021-28021/com.google.ads.rewardedvideoexample I/chromium: [INFO:CONSOLE(0)] "Application Cache NoUpdate event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
09-28 18:11:33.036 28021-28208/com.google.ads.rewardedvideoexample E/NativeCrypto: ssl=0xa0f7da00 cert_verify_callback x509_store_ctx=0xa1266280 arg=0x0
09-28 18:11:33.036 28021-28208/com.google.ads.rewardedvideoexample E/NativeCrypto: ssl=0xa0f7da00 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_ECDSA
09-28 18:11:33.445 28021-28208/com.google.ads.rewardedvideoexample I/System.out: gba_cipher_suite:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
09-28 18:11:33.446 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [OkHttp] sendRequest>>
09-28 18:11:33.447 28021-28208/com.google.ads.rewardedvideoexample I/System.out: [OkHttp] sendRequest<<
09-28 18:11:34.371 28021-28088/com.google.ads.rewardedvideoexample W/Ads: Fail to instantiate adapter com.google.DummyAdapter
                                                                          android.os.RemoteException
                                                                              at com.google.android.gms.internal.zzus.zzbj(Unknown Source)
                                                                              at com.google.android.gms.internal.zzus.zzbi(Unknown Source)
                                                                              at com.google.android.gms.internal.zzus.zzbg(Unknown Source)
                                                                              at com.google.android.gms.internal.zzacz.zzbt(Unknown Source)
                                                                              at com.google.android.gms.internal.zzaed.zzdc(Unknown Source)
                                                                              at com.google.android.gms.internal.zzafx.run(Unknown Source)
                                                                              at com.google.android.gms.internal.zzahc.call(Unknown Source)
                                                                              at com.google.android.gms.internal.zzahd.run(Unknown Source)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:818)
09-28 18:11:34.374 28021-28021/com.google.ads.rewardedvideoexample W/Ads: Failed to load ad: 3

**Comment by stowy** [comment] 2017-09-28 17:59
Hi @RoshaanQurban, thanks for your query, this is a different error code, the error code 3 means No fill. 

It may be because your adUnit hasn't yet been fully propogated through the system. It takes some time for the ad unit to be accepted into the system after you create it, and during that time you are likely to get these no fill responses.

I suggest you wait 24 hours from when you create your ad unit before you should expect to see it filling ad requests successfully.
