### ISSUE TITLE
Interstitial delay call onAdClosed() method on android P API 28.

### ISSUE THREAD

**Issue by hoangtunho2611** [googleads/googleads-mobile-android-examples#147] opened 2018-12-12 01:40 UTC
Hi,

I tested on android P API 28. I see delay after press "Skip Ads" or press key Back to close ads. Delay for 2-3 seconds then call onAdClosed (). This issue only occurs with interstitial ads containing video.

I test on: ads version 17.1.1/ 17.1.2 , target SDK 26, build tool 28.0.3

**Comment by stowy** [comment] 2018-12-26 03:30
Hi, thanks for your query.

I tested this in our sample interstitial app and wasn't able to reproduce using a Pixel XL on API 28. Can you provide additional repro information?

Additionally, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**Comment by stowy** [comment] 2019-01-02 18:43
Closing as unable to reproduce. Can re-open if further repro info is provided.

**Closed by stowy** 2019-01-02 18:43 UTC

**Comment by kenumir** [comment] 2020-09-11 13:19
I have facing same issue.
Its reported by others: 
https://groups.google.com/g/google-admob-ads-sdk/c/eW7-7N9e6UA
https://groups.google.com/g/google-admob-ads-sdk/c/GsJtshM_76c/m/AfhYcznCBQAJ

Maybe it's a problem with releasing resources for a video ad?

**Comment by DineshNeupane** [comment] 2021-04-04 07:07
Same issue with Interstial ads(video only). Other interstial formats i.e. Text, image, and rich media works fine without delay but when a Interstial Video ad is loaded there's a delay of about 2-3 seconds.
