### ISSUE TITLE
load ad fail.version 9.0.0

### ISSUE THREAD

**Issue by amswf** [googleads/googleads-mobile-android-examples#24] opened 2016-05-27 02:25 UTC
05-27 09:51:48.659 2069-2069/com.adwhile.demo W/GooglePlayServicesUtil: Cannot find Google Play services package name.
                                                                        android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
                                                                            at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:125)
                                                                            at com.google.android.gms.internal.zzpv.getPackageInfo(Unknown Source)
                                                                            at com.google.android.gms.common.zze.zzap(Unknown Source)
                                                                            at com.google.android.gms.common.zze.zzao(Unknown Source)
                                                                            at com.google.android.gms.common.zze.zzaj(Unknown Source)
                                                                            at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
                                                                            at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
                                                                            at com.google.android.gms.ads.internal.util.client.zza.zzQ(Unknown Source)
                                                                            at com.google.android.gms.ads.internal.client.zzl.zza(Unknown Source)
                                                                            at com.google.android.gms.ads.internal.client.zzl.zzl(Unknown Source)
                                                                            at com.google.android.gms.ads.internal.client.zzag.zza(Unknown Source)
                                                                            at com.google.android.gms.ads.MobileAds.initialize(Unknown Source)
                                                                            at com.google.android.gms.ads.MobileAds.initialize(Unknown Source)
                                                                            at com.adwhile.demo.MainActivity.onCreate(MainActivity.java:58)
                                                                            at android.app.Activity.performCreate(Activity.java:6104)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2566)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2682)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1539)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5779)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
05-27 09:51:48.660 2069-2069/com.adwhile.demo W/GooglePlayServicesUtil: Google Play services is missing.
05-27 09:51:48.711 2069-2069/com.adwhile.demo W/GooglePlayServicesUtil: Google Play services is missing.
05-27 09:51:48.771 2069-2069/com.adwhile.demo I/WebViewFactory: Loading com.android.webview version 1.0 (code 400002)
05-27 09:51:48.773 2069-2106/com.adwhile.demo W/GooglePlayServicesUtil: Google Play services is missing.
05-27 09:51:48.773 2069-2106/com.adwhile.demo W/GooglePlayServicesUtil: Google Play services is missing.
05-27 09:51:48.780 2069-2069/com.adwhile.demo I/LibraryLoader: Time to load native libraries: 3 ms (timestamps 1872-1875)
05-27 09:51:48.780 2069-2069/com.adwhile.demo I/LibraryLoader: Expected native library version number "",actual native library version number ""
05-27 09:51:48.783 2069-2069/com.adwhile.demo I/LibraryLoader: Expected native library version number "",actual native library version number ""
05-27 09:51:48.783 2069-2069/com.adwhile.demo I/chromium: [INFO:library_loader_hooks.cc(108)] Chromium logging enabled: level = 0, default verbosity = 0
05-27 09:51:48.789 2069-2069/com.adwhile.demo I/BrowserStartupController: Initializing chromium process, singleProcess=true
05-27 09:51:48.789 2069-2069/com.adwhile.demo W/art: Attempt to remove local handle scope entry from IRT, ignoring
05-27 09:51:48.797 2069-2069/com.adwhile.demo W/chromium: [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
05-27 09:51:48.798 2069-2069/com.adwhile.demo I/chromium: [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=41 off=1382828 len=3242
05-27 09:51:48.798 2069-2069/com.adwhile.demo I/chromium: [INFO:aw_browser_main_parts.cc(76)] Loading webviewchromium.pak from, fd:42 off:239276 len:1143506
05-27 09:51:48.819 2069-2069/com.adwhile.demo E/GED: Failed to get GED Log Buf, err(0)
05-27 09:51:48.841 2069-2069/com.adwhile.demo E/ProxyChangeListener: [getProperty] propertyValue is isEmpty .
05-27 09:51:48.841 2069-2069/com.adwhile.demo E/ProxyChangeListener: [getProperty] final: http.proxyHost = null
05-27 09:51:48.841 2069-2069/com.adwhile.demo E/ProxyChangeListener: [getProperty] propertyValue is isEmpty .
05-27 09:51:48.841 2069-2069/com.adwhile.demo E/ProxyChangeListener: [getProperty] final: https.proxyHost = null
05-27 09:51:48.846 2069-2069/com.adwhile.demo E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-27 09:51:48.858 2069-2069/com.adwhile.demo I/Ads: Starting ad request.
05-27 09:51:48.916 2069-2144/com.adwhile.demo W/GooglePlayServicesUtil: Google Play services is missing.
05-27 09:51:48.917 2069-2144/com.adwhile.demo W/Ads: Failed to connect to remote ad request service.
05-27 09:51:48.917 2069-2144/com.adwhile.demo W/Ads: Could not start the ad request service.
05-27 09:51:48.935 2069-2069/com.adwhile.demo I/ProxyChangeListener: [checkHostAndPortLegality] host:, port:0, ret:true
05-27 09:51:48.935 2069-2069/com.adwhile.demo E/ProxyChangeListener: [onReceive] proxyConfig : com.android.org.chromium.net.ProxyChangeListener$ProxyConfig@e4f6c56, mTurborHost:null, mTurborPort:0
05-27 09:51:48.954 2069-2145/com.adwhile.demo I/OpenGLRenderer: Initialized EGL, version 1.4
05-27 09:51:48.954 2069-2145/com.adwhile.demo W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
05-27 09:51:48.957 2069-2069/com.adwhile.demo W/Ads: Failed to load ad: 0

**Comment by RedBrogdon** [comment] 2016-05-27 23:17
Thank you for the stacktrace. Without context, though, it's hard to act on. Can you provide more detail, such as:

- Device Type
- OS version
- Version of Google Play services on the device
- Steps to reproduce the crash

**Comment by rampara** [comment] 2016-09-29 15:40
Closing issue due to its age. If this issue still persists for you, please re-open it.

**Closed by rampara** 2016-09-29 15:40 UTC
