### ISSUE TITLE
Rewarded Video Ads never die with mRewardedVideoAd.destroy(this);

### ISSUE THREAD

**Issue by murgupluoglu** [googleads/googleads-mobile-android-examples#83] opened 2017-07-28 09:16 UTC
I just add a TestActivity at sample admob/RewardedVideoExample/ 

First, start with TestActivity and open MainActivity later that. Ads start to load. close MainActivity and back to TestActivity. When ads load from server our mRewardedVideoAd still alive and toast message onRewardedVideoAdLoaded. I can't destroy it with mRewardedVideoAd.destroy(this); how i can solve that?

**Comment by stowy** [comment] 2017-08-01 18:43
Hi @murgupluoglu, thanks for the issue. I have replicated the behavior, you are correct, the listener callbacks are still received after `destroy(this)` is called on the RewardedVideoAd. Our team will investigate and report back when we have an update.

**Comment by stowy** [comment] 2017-08-08 22:59
Hi @murgupluoglu, as a workaround solution for this, you should explicitly unset the listener for the RewardedVideoAd before you call destroy, as destroy will not do this for you. We are working on a fix for this as well as related issue #84.

**Comment by ParkerK** [comment] 2017-08-18 22:51
@stowy - do you mean set the listener to null? If so, doing that didn't fix the leak for me, I still get:
Handler (com.google.android.gms.ads.exoplayer1.upstream.o) {90c614} sending message to a Handler on a dead thread

**Comment by stowy** [comment] 2017-08-21 03:56
Hi @ParkerK - this won't stop the RewardedVideo leaking the activity. When you instantiate an instance of the rewarded with an activity context, that activity context may be leaked currently. 

I think a workaround for this is to instantiate the instance with the application context, but then do all other calls such as resume by passing in the activity context. 

Setting the listener to null on the rewarded video will stop the listener being called though I believe.

**Comment by prateekarora** [comment] 2017-12-15 08:23
Hi @stowy,
Any ETA updates on fix for #83 and #84? It is still happening in com.google.firebase:firebase-ads:11.6.2

**Comment by stowy** [comment] 2018-01-04 22:51
hi @prateekarora - no updates at this stage but thanks for the ping. Will update again once a solution has been identified.

**Comment by Testencio** [comment] 2018-01-26 19:10
Hi @stowy 

> I think a workaround for this is to instantiate the instance with the application context, but then do all other calls such as resume by passing in the activity context.

Some adapters (like UnityAdapter) require an activity context so seems i'll keep leaking my activities until this get fixed :(

Btw, interstitialAd class doesn't have destroy() method. It's very strange...

Thanks!

**Comment by stowy** [comment] 2018-02-05 17:40
@Testencio what i suggested in my comment is to instantiate using application context and then make other calls using activity context. This should work fine with Unity, etc, as long as you pass the activity context in the calls like `pause(Context context)` and `resume(Context context)`.

I believe interstitial doesn't need a destroy method because it's not a singleton class and therefore should be destroyed automatically when garbage collected. Rewarded video is a singleton and therefore will continue to live outside of activities, which is the cause of the issues seen here.

**Comment by Testencio** [comment] 2018-02-06 23:20
@stowy Thank you so much, it was very helpful.

**Comment by stowy** [comment] 2018-02-13 17:09
No problems.

**Comment by Testencio** [comment] 2018-03-12 23:50
@stowy Hi again stowy and sorry for disturbing 1 month later,

I noticed that my leaks disappeared but checking my mediation logs in Android Studio appears this warning:

```
I/Ads: Instantiating mediation adapter: com.google.ads.mediation.unity.UnityAdapter
W/UnityAdapter: Context is not an Activity. Unity Ads requires an Activity context to load ads.
```

I'm building my insterstitialAd this way:
`interstitialAd = new InterstitialAd(getApplicationContext());` no leak - no unity ads

But if i use my activity context instead of the application context the warning disappears and my activity leaks. 

`interstitialAd = new InterstitialAd(this);` leak - unity ads ok

I'm doing something wrong or i have to wait for the fix? Thanks in advance!

**Comment by stowy** [comment] 2018-03-14 16:02
Hi @Testencio that's interesting, thanks for the info. I will discuss with the engineers on our end, but it appears that you have run into a legitimate issue. I'll update with more info on a resolution when available.

**Comment by caroparo** [comment] 2019-02-17 04:06
@stowy 
Hi, is there any update on the UnityAdapter issue? I'm trying to integrate unity ads mediation; the beta MediationTestSuite shows that I got everything ok (SDK,adapter,Game ID, placement ID), but both interstitial and rewarded ads showed "internal error", with mediation logs saying:
```
I/Ads: Instantiating mediation adapter: com.google.ads.mediation.unity.UnityAdapter
W/UnityAdapter: Context is not an Activity. Unity Ads requires an Activity context to load ads.
```

Does this mean that UnityAds currently does not work with AdMob mediation? 
I saw a similar issue: [here](https://github.com/invertase/react-native-firebase/pull/1892)

Sorry if this is not the right place to report/ask about the issue; please let me know where I should look for further help if that's the case. Thanks!

**Comment by ahsan-malik** [comment] 2022-08-04 06:13
I was facing the same issue in interstitial ad and it is resolved by setting the  FullScreenContentCallback to null in all of its overridden methods.

**Comment by ericleich** [comment] 2022-08-04 19:12
I'm going to close this issue as obsolete. The rewarded API from 2017 was static and only let you load 1 ad at a time, and some of the nature of those APIs made it such that objects weren't cleaned up properly.

With the latest SDK, you can have many rewarded ad instances, and dropping your reference to the rewarded ad should end up garbage collecting the rewarded ad and adapter instances that the rewarded ad refers to.

**Closed by ericleich** 2022-08-04 19:12 UTC
Labels: bug
