### ISSUE TITLE
Fail to instantiate adapter com.google.DummyAdapter

### ISSUE THREAD

**Issue by huyongli** [googleads/googleads-mobile-android-examples#102] opened 2017-12-19 09:59 UTC
Failed to load ad: 3  and Fail to instantiate adapter com.google.DummyAdapter

**Comment by ericleich** [comment] 2017-12-20 18:01
This is a somewhat misleading message, it just means no fill. Did this happen when using the sample ad units?

**Comment by huyongli** [comment] 2017-12-21 08:18
@ericleich  Yes, using the sample ad units have same problem

**Comment by stowy** [comment] 2018-01-03 17:59
@huyongli if this is occurring in a sample app, can you please advise which sample app it is and steps to reproduce the issue?

**Comment by stowy** [comment] 2018-01-12 16:22
closing as unable to reproduce.

**Closed by stowy** 2018-01-12 16:22 UTC
