### ISSUE TITLE
RewardedVideoAdListener not called sometime

### ISSUE THREAD

**Issue by wysgh** [googleads/googleads-mobile-android-examples#104] opened 2017-12-27 14:37 UTC
When I close Video or watch all video ,onRewardedVideoAdClosed,and onRewarded not called sometime

**Comment by stowy** [comment] 2018-01-03 23:52
Hi @wysgh, I was unable to reproduce this issue with our Rewarded Video sample app.

Can you please provide specific steps to reproduce?

If the problem is specific to your application, can you please make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**Comment by stowy** [comment] 2018-01-12 16:22
closing as unable to reproduce.

**Closed by stowy** 2018-01-12 16:22 UTC
