### ISSUE TITLE
Application Cache NoUpdate event error android

### ISSUE THREAD

**Issue by adamdao1** [googleads/googleads-mobile-android-examples#105] opened 2017-12-31 14:57 UTC
Application Cache NoUpdate event error android
![13w](https://user-images.githubusercontent.com/34807890/34462355-dd921088-ee74-11e7-8c8c-3afdc968bcdb.PNG)
![13a](https://user-images.githubusercontent.com/34807890/34462367-ffbb882e-ee74-11e7-98a0-09471554f5a2.PNG)

**Comment by stowy** [comment] 2018-01-03 18:06
hi @adamdao1 can you please advise which sample app this error is occurring in and the steps to reproduce?

If the issue is not in a sample app, can you please advise and file a request on the [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android so we can better assist you in debugging your issue.

**Comment by stowy** [comment] 2018-01-12 16:22
closing as unable to reproduce.

**Closed by stowy** 2018-01-12 16:22 UTC
