### ISSUE TITLE
IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by NiaNingXue** [googleads/googleads-mobile-android-examples#169] opened 2019-07-02 00:45 UTC
```
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.K@c674969
       at android.app.LoadedApk.forgetServiceDispatcher + 1352(LoadedApk.java:1352)
       at android.app.ContextImpl.unbindService + 1553(ContextImpl.java:1553)
       at android.content.ContextWrapper.unbindService + 723(ContextWrapper.java:723)
       at com.google.android.gms.common.stats.ConnectionTracker.getInstance(ConnectionTracker.java:1)
       at com.google.android.gms.common.internal.zzf.zzf(zzf.java:40)
       at com.google.android.gms.common.internal.zze.handleMessage(zze.java:39)
       at android.os.Handler.dispatchMessage + 98(Handler.java:98)
       at com.google.android.gms.internal.common.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6776(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1518(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main + 1408(ZygoteInit.java:1408)
```

**Comment by stowy** [comment] 2019-07-02 23:18
Hi, please provide more information about how to reproduce this issue and
which sample application you are using.

If this is related to your own application, please post in our support forum
<https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android>.

Regards

Sam

**Comment by stowy** [comment] 2019-07-08 22:50
Closing as cannot reproduce.

**Closed by stowy** 2019-07-08 22:50 UTC
