### ISSUE TITLE
RewardedVideoAd：Failed to load ad: 3

### ISSUE THREAD

**Issue by LuoGuoXin** [googleads/googleads-mobile-android-examples#67] opened 2017-04-11 07:39 UTC
04-11 15:37:27.427 24840-24840/com.google.ads.rewardedvideoexample E/chromium: [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
04-11 15:37:28.304 24840-3333/com.google.ads.rewardedvideoexample W/Ads: Fail to instantiate adapter com.google.DummyAdapter
                                                                         android.os.RemoteException
                                                                             at com.google.android.gms.internal.zzjz.zzav(Unknown Source)
                                                                             at com.google.android.gms.internal.zzjz.zzau(Unknown Source)
                                                                             at com.google.android.gms.internal.zzjz.zzas(Unknown Source)
                                                                             at com.google.android.gms.internal.zzns.zzaN(Unknown Source)
                                                                             at com.google.android.gms.internal.zzok.zza(Unknown Source)
                                                                             at com.google.android.gms.internal.zzok.zzco(Unknown Source)
                                                                             at com.google.android.gms.internal.zzpj$1.run(Unknown Source)
                                                                             at com.google.android.gms.internal.zzpn$2.zzbk(Unknown Source)
                                                                             at com.google.android.gms.internal.zzpn$2.call(Unknown Source)
                                                                             at com.google.android.gms.internal.zzpn$3.run(Unknown Source)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-11 15:37:28.304 24840-24840/com.google.ads.rewardedvideoexample W/Ads: Failed to load ad: 3
04-11 15:37:32.393 24840-3339/com.google.ads.rewardedvideoexample V/FA: Inactivity, disconnecting from the service

**Comment by ericleich** [comment] 2017-04-11 15:41
Duplicate of https://github.com/googleads/googleads-mobile-android-examples/issues/65

**Closed by ericleich** 2017-04-11 15:41 UTC
Labels: duplicate
