### ISSUE TITLE
Incorrect behavior of Rewarded Ad in portrait mode

### ISSUE THREAD

**Issue by dpershin** [googleads/googleads-mobile-android-examples#82] opened 2017-07-10 14:48 UTC
Hi everyone!

Actually, I faced this behavior during Admob integration into Unity project, I even filed a bug about it: https://github.com/googleads/googleads-mobile-unity/issues/458. Initially, I thought it was a bug in plugin/Unity, but then decided to dig deeper. I've tried it on Rewarded Ad Example and have got the very same result. Here are reproduction steps:

1. Download and unzip RewardedVideoExample
2. Build and run the example in portrait mode
3. Wait until ad is loaded and press "Watch video..." button 

Result:
The video starts playing but with some UI bugs:
- No sound control button
- Video is displayed in landscape layout though UI is in portrait layout
- No download button and no any reaction on tapping on the screen
- When video ends the counter freezes at 1 second
- You can scroll video horizontally/vertically

The interesting thing is if you run the app in the landscape mode everything works perfectly, even if you rotate a device to portrait mode (first play video in landscape). 

My environment:
1. Build tools: 25.0.2, 25.0.3
2. Min SDK: 14
3. Target SDK: 25
4. Google Play Services: didn't change from the example
5. Phones: Nexus 5, Huawei Honor 4C Pro

I don't attach the screenshot, it takes a lot of space (I don't know how to reduce it), but you can find it on the link to bug report above.

Thank you!

**Comment by ericleich** [comment] 2017-07-13 00:53
I couldn't reproduce on my end. Ram's suggestion in the other ticket to contact the developer forum is the right call.

When the video ad comes back, it does have an orientation associated with it. It sounds like somehow you got the video to play in the orientation it's not supposed to be in. On my end, if I requested the ad while in portrait, and a portrait video comes back, then even if I rotate to landscape before showing it, the video plays in portrait mode.

**Comment by dpershin** [comment] 2017-07-20 14:11
Hi!

Sorry, I missed your answer and thanks for the advice! Actually, I did as you suggested. Here is the thread on official forum: https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/HAd_FsTjGKE

**Comment by ericleich** [comment] 2017-07-20 16:18
Thanks @dpershin . I'm going to close this issue as discussion is active on the forum.

**Closed by ericleich** 2017-07-20 16:18 UTC
