### ISSUE TITLE
AdView is Blank!

### ISSUE THREAD

**Issue by JeniferJethrouth** [googleads/googleads-mobile-android-examples#55] opened 2017-03-03 06:33 UTC
Admob is not visible. It  worked fine before a month but now its not at all visible in many devices. Even test ad also not working. Rarely admob comes, most of the time the view is blank only.

**Comment by ericleich** [comment] 2017-03-03 16:44
Which format are you using?

Test ads weren't working 2 days ago but should have been fixed before your comment 10 hours ago.

**Comment by JeniferJethrouth** [comment] 2017-03-06 09:47
Sometime adview is visible sometime is empty. Its not working,even i changed  Ad unit id .

**Comment by ericleich** [comment] 2017-03-06 16:51
I need more information to help you debug. Are you running one of the samples from this repo and still not getting ads back? Which one?

**Comment by JeniferJethrouth** [comment] 2017-03-13 10:26
Yes i checked BannerExample project. am not getting ads. its saying error code 2. i also switched from wifi to mobile data ,Ad is coming one time after some time its not at all coming. i also checked with many devices

**Comment by ericleich** [comment] 2017-03-15 16:07
I'm getting back the banner ad when downloading and running the AdMob Banner example out of the box, so it's not a network-wide problem.

Error code 2 is a [network error](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.html#ERROR_CODE_NETWORK_ERROR).  Can you confirm:

1. You can use Chrome to successfully access the internet
2. Your device doesn't have an ad blocker installed

**Comment by ericleich** [comment] 2017-03-27 21:23
Closing this issue as duplicate of #60

**Closed by ericleich** 2017-03-27 21:23 UTC
