### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by josaliba** [googleads/googleads-mobile-android-examples#18] opened 2015-08-27 13:14 UTC
Hi,

I am trying the double click example for interstitial ads using the provided ad unit id /6499/example/interstitial but I never receive an ad. It always returns no ad to fill from server.
Same thing is also happening with iOS example too.

Can you please confirm that the example is broken? Or is something wrong with the ad unit id.

Thank you

**Comment by ericleich** [comment] 2015-08-29 01:35
Something is wrong with that particular ad unit ID. We haven't found the root cause yet, however.

**Comment by josaliba** [comment] 2015-09-06 05:48
Thank you for your response.

I have also tried using my unit ad Id using  the example app provided. But it is not working. Is it possible that something is wrong with DFP serving AdMob ads? Especially that this feature is still in BETA?

**Comment by ericleich** [comment] 2015-09-10 01:27
If you are getting a no-fill from DFP, it's probably a setup-specific problem. For example, your line item should be targeting a 320x480 or 480x320 ad size depending on orientation, and your ad unit should support those sizes too.

**Comment by RedBrogdon** [comment] 2015-10-17 00:12
I'm going to close this for now. If anyone's still not getting fill on our DFP test interstitials, go ahead and reopen.

**Closed by RedBrogdon** 2015-10-17 00:12 UTC
